Евгений Сергеевич, если вы это читаете, прошу строго не судить за этот код :)

In [14]:
PATH = "../Datasets/UCI Dynamic Gas Mixtures"

In [5]:
!pip install pandas matplotlib

Collecting pandas
  Using cached pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Using cached matplotlib-3.11.1-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.65.0-cp314-cp314-win_amd64.whl.metadata (127 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
Using cached matplotlib-3.11.1-cp314-cp314-win_amd64.whl (9.5 MB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.65.0-cp314-cp314-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.5 MB 1.5 MB/s eta 0:00:02
   ---------------- ----------------------- 1.0/2.5 MB 1.6 MB/s eta 0:00:01
   --------------------- ------------------ 1.3/2.5 MB 1.7 MB/s eta 0:00:01
   ----------------------------- ---------- 1.8/2.5 MB 1.7 MB/s eta 0:00:01
   --------------------------------- ------ 2.1/2.5 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 1.7 MB/s  0:00:01
Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl (72 kB)
Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.7 MB 1.9 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.7 MB 1.9 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.7 MB 1.5 MB/s eta 0:00:08
   ---- ----------------------------------- 1.6/12.7 MB 1.5 MB/s eta 0:00:08
   ----- ---------------------------------- 1.8/12.7 MB 1.5 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.7 MB 1.5 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/12.7 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.7 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 3.1/12.7 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/12.7 MB 1.5 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.7 MB 1.5 MB/s eta 0:00:07
   ------------- -------------------------- 4.2/12.7 MB 1.5 MB/s eta 0:00:06
   -------------- ------------------------- 4.5/12.7 MB 1.5 MB/s eta 0:00:06
   -------------- ------------------------- 4.7/12.7 MB 1.5 MB/s eta 0:00:06
   --------------- ------------------------ 5.0/12.7 MB 1.5 MB/s eta 0:00:06
   ---------------- ----------------------- 5.2/12.7 MB 1.5 MB/s eta 0:00:06
   ----------------- ---------------------- 5.5/12.7 MB 1.5 MB/s eta 0:00:05
   ------------------ --------------------- 5.8/12.7 MB 1.5 MB/s eta 0:00:05
   ------------------ --------------------- 6.0/12.7 MB 1.5 MB/s eta 0:00:05
   ------------------- -------------------- 6.3/12.7 MB 1.4 MB/s eta 0:00:05
   --------------------- ------------------ 6.8/12.7 MB 1.4 MB/s eta 0:00:05
   ---------------------- ----------------- 7.1/12.7 MB 1.4 MB/s eta 0:00:04
   ---------------------- ----------------- 7.1/12.7 MB 1.4 MB/s eta 0:00:04
   ----------------------- ---------------- 7.3/12.7 MB 1.4 MB/s eta 0:00:04
   ----------------------- ---------------- 7.6/12.7 MB 1.4 MB/s eta 0:00:04
   ----------------------- ---------------- 7.6/12.7 MB 1.4 MB/s eta 0:00:04
   ------------------------ --------------- 7.9/12.7 MB 1.3 MB/s eta 0:00:04
   ------------------------- -------------- 8.1/12.7 MB 1.3 MB/s eta 0:00:04
   ------------------------- -------------- 8.1/12.7 MB 1.3 MB/s eta 0:00:04
   -------------------------- ------------- 8.4/12.7 MB 1.3 MB/s eta 0:00:04
   -------------------------- ------------- 8.4/12.7 MB 1.3 MB/s eta 0:00:04
   --------------------------- ------------ 8.7/12.7 MB 1.2 MB/s eta 0:00:04
   --------------------------- ------------ 8.7/12.7 MB 1.2 MB/s eta 0:00:04
   --------------------------- ------------ 8.7/12.7 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 8.9/12.7 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 8.9/12.7 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 8.9/12.7 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 9.2/12.7 MB 1.1 MB/s eta 0:00:04
   ---------------------------- ----------- 9.2/12.7 MB 1.1 MB/s eta 0:00:04
   ---------------------------- ----------- 9.2/12.7 MB 1.1 MB/s eta 0:00:04
   ----------------------------- ---------- 9.4/12.7 MB 1.0 MB/s eta 0:00:04
   ----------------------------- ---------- 9.4/12.7 MB 1.0 MB/s eta 0:00:04
   ----------------------------- ---------- 9.4/12.7 MB 1.0 MB/s eta 0:00:04
   ------------------------------ --------- 9.7/12.7 MB 1.0 MB/s eta 0:00:03
   ------------------------------ --------- 9.7/12.7 MB 1.0 MB/s eta 0:00:03
   ------------------------------- -------- 10.0/12.7 MB 981.1 kB/s eta 0:00:03
   ------------------------------- -------- 10.0/12.7 MB 981.1 kB/s eta 0:00:03
   ------------------------------- -------- 10.0/12.7 MB 981.1 kB/s eta 0:00:03
   -------------------------------- ------- 10.2/12.7 MB 945.5 kB/s eta 0:00:03
   -------------------------------- ------- 10.2/12.7 MB 945.5 kB/s eta 0:00:03
   -------------------------------- ------- 10.2/12.7 MB 945.5 kB/s eta 0:00:03
   --------------------------------- ------ 10.5/12.7 MB 921.0 kB/s eta 0:00:03
   --------------------------------- ------ 10.5/12.7 MB 921.0 kB/s eta 0:00:03
   --------------------------------- ------ 10.7/12.7 MB 902.5 kB/s eta 0:00:03
   --------------------------------- ------ 10.7/12.7 MB 902.5 kB/s eta 0:00:03
   ---------------------------------- ----- 11.0/12.7 MB 887.1 kB/s eta 0:00:02
   ---------------------------------- ----- 11.0/12.7 MB 887.1 kB/s eta 0:00:02
   ---------------------------------- ----- 11.0/12.7 MB 887.1 kB/s eta 0:00:02
   ----------------------------------- ---- 11.3/12.7 MB 874.6 kB/s eta 0:00:02
   ----------------------------------- ---- 11.3/12.7 MB 874.6 kB/s eta 0:00:02
   ------------------------------------ --- 11.5/12.7 MB 860.1 kB/s eta 0:00:02
   ------------------------------------ --- 11.5/12.7 MB 860.1 kB/s eta 0:00:02
   ------------------------------------ --- 11.5/12.7 MB 860.1 kB/s eta 0:00:02
   ------------------------------------- -- 11.8/12.7 MB 842.5 kB/s eta 0:00:02
   ------------------------------------- -- 11.8/12.7 MB 842.5 kB/s eta 0:00:02
   ------------------------------------- -- 12.1/12.7 MB 828.1 kB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.7 MB 828.1 kB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.7 MB 828.1 kB/s eta 0:00:01
   -------------------------------------- - 12.3/12.7 MB 810.5 kB/s eta 0:00:01
   -------------------------------------- - 12.3/12.7 MB 810.5 kB/s eta 0:00:01
   -------------------------------------- - 12.3/12.7 MB 810.5 kB/s eta 0:00:01
   ---------------------------------------  12.6/12.7 MB 796.0 kB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 787.5 kB/s  0:00:15
Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pyparsing, pillow, numpy, kiwisolver, fonttools, cycler, pandas, contourpy, matplotlib

   ----------------------------------------  0/10 [tzdata]
   ----------------------------------------  0/10 [tzdata]
   ----------------------------------------  0/10 [tzdata]
   ---- -----------------------------------  1/10 [pyparsing]
   ---- -----------------------------------  1/10 [pyparsing]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   -------------------------------- -------  8/10 [contourpy]
   -------------------------------- -------  8/10 [contourpy]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
ethylene_co = pd.read_csv(PATH + "/ethylene_CO.txt", sep=r'\s+', skiprows=1, names=['Time', 'Methane', 'Ethylene'] + [f's{i}' for i in range(1, 17)])

In [33]:
ethylene_co

,Time,Methane,Ethylene,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16
0,0.00,0.0,0.0,-50.85,-1.95,-41.82,1.30,-4.07,-28.73,-13.49,-3.25,55139.95,50669.50,9626.26,9762.62,24544.02,21420.68,7650.61,6928.42
1,0.01,0.0,0.0,-49.40,-5.53,-42.78,0.49,3.58,-34.55,-9.59,5.37,54395.77,50046.91,9433.20,9591.21,24137.13,20930.33,7498.79,6800.66
2,0.01,0.0,0.0,-40.04,-16.09,-27.59,0.00,-7.16,-42.14,-12.52,-5.86,53960.02,49299.30,9324.40,9449.81,23628.90,20504.94,7369.67,6697.47
3,0.03,0.0,0.0,-47.14,-10.57,-32.28,4.40,-11.22,-37.94,-7.16,-1.14,53047.71,48907.00,9170.64,9305.58,23101.66,20101.42,7285.13,6578.52
4,0.04,0.0,0.0,-33.58,-20.79,-33.25,6.03,3.42,-34.22,-14.46,8.31,52700.28,48330.96,9073.64,9163.47,22689.54,19694.07,7156.74,6468.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4208256,42087.51,0.0,0.0,1127.81,105.93,2117.39,2247.58,1207.59,1646.73,2089.97,2262.98,1061.70,1070.47,2570.33,2073.57,709.06,775.36,2513.75,1848.65
4208257,42087.52,0.0,0.0,1140.73,96.46,2105.93,2253.69,1216.39,1624.47,2073.57,2246.61,1063.89,1075.26,2580.88,2083.78,698.24,768.93,2511.20,1843.63
4208258,42087.53,0.0,0.0,1123.99,107.92,2111.18,2245.63,1215.36,1628.44,2085.45,2271.80,1059.31,1063.49,2583.20,2090.20,709.62,775.73,2510.18,1841.80
4208259,42087.54,0.0,0.0,1131.44,111.08,2114.76,2249.54,1197.99,1612.17,2078.32,2272.29,1063.69,1066.08,2578.56,2100.92,716.72,779.14,2508.91,1851.17
4208260,42087.55,0.0,0.0,1130.23,98.45,2107.12,2255.64,1211.07,1621.62,2085.92,2271.31,1071.07,1079.05,2577.28,2071.91,701.78,772.52,2530.08,1864.44

In [34]:
ethylene_co.head()

,Time,Methane,Ethylene,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16
0,0.00,0.0,0.0,-50.85,-1.95,-41.82,1.30,-4.07,-28.73,-13.49,-3.25,55139.95,50669.50,9626.26,9762.62,24544.02,21420.68,7650.61,6928.42
1,0.01,0.0,0.0,-49.40,-5.53,-42.78,0.49,3.58,-34.55,-9.59,5.37,54395.77,50046.91,9433.20,9591.21,24137.13,20930.33,7498.79,6800.66
2,0.01,0.0,0.0,-40.04,-16.09,-27.59,0.00,-7.16,-42.14,-12.52,-5.86,53960.02,49299.30,9324.40,9449.81,23628.90,20504.94,7369.67,6697.47
3,0.03,0.0,0.0,-47.14,-10.57,-32.28,4.40,-11.22,-37.94,-7.16,-1.14,53047.71,48907.00,9170.64,9305.58,23101.66,20101.42,7285.13,6578.52
4,0.04,0.0,0.0,-33.58,-20.79,-33.25,6.03,3.42,-34.22,-14.46,8.31,52700.28,48330.96,9073.64,9163.47,22689.54,19694.07,7156.74,6468.32

In [35]:
ethylene_co.shape

(4208261, 19)

In [37]:
ethylene_co.info()

<class 'pandas.DataFrame'>
RangeIndex: 4208261 entries, 0 to 4208260
Data columns (total 19 columns):
 #   Column    Dtype
---  ------    -----
 0   Time      float64
 1   Methane   float64
 2   Ethylene  float64
 3   s1        float64
 4   s2        float64
 5   s3        float64
 6   s4        float64
 7   s5        float64
 8   s6        float64
 9   s7        float64
 10  s8        float64
 11  s9        float64
 12  s10       float64
 13  s11       float64
 14  s12       float64
 15  s13       float64
 16  s14       float64
 17  s15       float64
 18  s16       float64
dtypes: float64(19)
memory usage: 610.0 MB

In [38]:
ethylene_co.describe().round(2)

,Time,Methane,Ethylene,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16
count,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00,4208261.00
mean,21044.59,127.62,5.32,2065.62,506.22,4372.54,4799.25,1894.96,2214.69,5086.64,5385.43,1186.24,1219.25,4871.08,3926.25,928.19,1035.77,5289.32,4309.69
std,12149.98,160.78,5.62,790.26,1530.13,1608.02,1733.02,439.54,435.40,1966.45,2072.38,453.17,430.88,1707.68,1364.50,167.76,174.11,1984.06,1584.04
min,0.00,0.00,0.00,-52.62,-36.49,-45.04,-8.94,-12.19,-42.14,-23.22,-13.82,159.74,215.31,862.22,865.49,609.57,673.89,546.73,488.58
25%,10521.23,0.00,0.00,1323.47,9.12,2986.96,3282.31,1503.46,1856.65,3241.95,3448.62,934.33,941.92,3435.68,2728.93,808.34,910.25,3642.12,2805.07
50%,21045.91,0.00,6.67,1789.09,38.89,4494.33,4946.72,1984.55,2272.78,5224.88,5537.91,1140.32,1176.60,5016.13,4120.24,929.86,1060.70,5320.55,4543.04
75%,31566.78,266.67,10.00,2869.44,158.90,5658.29,6178.21,2262.74,2566.47,6719.28,7104.20,1543.66,1557.78,6126.83,4967.48,1033.49,1161.37,6739.32,5565.07
max,42087.55,533.33,20.00,3553.64,28116.51,8641.34,9221.02,2904.04,3502.11,9883.50,10521.04,55139.95,50669.50,9626.26,9762.62,24544.02,21420.68,10665.30,7874.49

In [39]:
ethylene_co.isna().sum().sum()

np.int64(0)

In [41]:
ethylene_co.duplicated().sum()

np.int64(0)

In [43]:
ethylene_co['Time'].duplicated().sum()

np.int64(122672)

Не знаю, что с этим делать, тут есть дубликаты по времени. Пока ничего с этим не делал

с нормализацией пока сильно не заморачивался. Для этого надо будет для начала разбить на сплиты. Пока сделал просто мин-максом

In [47]:
normalize_columns = ['Methane', 'Ethylene'] + [f's{i}' for i in range(1, 17)]

In [48]:
def min_max_scaler(normalize_columns, ds):
    for col in normalize_columns:
        ds[col] = (ds[col] - ds[col].min()) / (ds[col].max() - ds[col].min())

In [49]:
min_max_scaler(normalize_columns, ethylene_co)

In [54]:
ethylene_co.describe().round(3)

,Time,Methane,Ethylene,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16
count,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000,4208261.000
mean,21044.591,0.239,0.266,0.587,0.019,0.509,0.521,0.654,0.637,0.516,0.513,0.019,0.020,0.457,0.344,0.013,0.017,0.469,0.517
std,12149.981,0.301,0.281,0.219,0.054,0.185,0.188,0.151,0.123,0.198,0.197,0.008,0.009,0.195,0.153,0.007,0.008,0.196,0.214
min,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,10521.230,0.000,0.000,0.382,0.002,0.349,0.357,0.520,0.536,0.330,0.329,0.014,0.014,0.294,0.209,0.008,0.011,0.306,0.314
50%,21045.910,0.000,0.334,0.511,0.003,0.523,0.537,0.685,0.653,0.530,0.527,0.018,0.019,0.474,0.366,0.013,0.019,0.472,0.549
75%,31566.780,0.500,0.500,0.810,0.007,0.657,0.670,0.780,0.736,0.681,0.676,0.025,0.027,0.601,0.461,0.018,0.023,0.612,0.687
max,42087.550,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000